web-monitoring/monitoring/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
import sitemonitor.urls
import performance.urls
import monitoring_server.urls

urlpatterns = [
    path('monitor/', include(sitemonitor.urls, namespace="monitor")),
    path('performance/', include(performance.urls, namespace="performance")),
    path('api/client/', include(monitoring_server.urls, namespace="monitoring_server")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-monitoring/sitemonitor/urls.py
from django.urls import include, path
from . import views

app_name = 'sitemonitor'

urlpatterns = [
    path('', views.monitor, name="monitor"),
    path('startmonitor/', views.startmonitor, name="startmonitor"),
    path('addmonitor/', views.addmonitor, name="addmonitor"),
    path('removemonitor/<int:pk>', views.removemonitor, name="removemonitor"),
    path('editmonitor/<int:pk>', views.editmonitor, name="editmonitor"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard/chart', views.ChartDetailsViewSet.as_view(), name="dashboard"),
    path('dashboard/performance', views.dashboard_performance.as_view(), name="dashboard_performance")
]

web-monitoring/sitemonitor/models.py
from django.db import models


# Create your models here.
class monitorDetails(models.Model):
    domainName = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=False, unique=False)
    interval = models.IntegerField(default=0)
    startDate = models.DateTimeField(blank=True, null=True)
    endDate = models.DateTimeField(blank=True, null=True)
    upTime = models.IntegerField(default=0)
    downTime = models.IntegerField(default=0)
    isNotification = models.BooleanField(default=True)
    notificationInterval = models.IntegerField(default=60)
    lastNotificationTime = models.DateTimeField(blank=True, null=True)
    SSLEnable = models.BooleanField(default=False)
    SSLInterval = models.IntegerField(default=0)

    isperfomance = models.BooleanField(default=False)
    perfomanceinterval = models.IntegerField(default=0)


class monitorCountDetails(models.Model):
    TYPES = [("up", "UP"), ("down", "DOWN")]
    monitorDetailsId = models.ForeignKey(monitorDetails, on_delete=models.CASCADE)
    startTime = models.DateTimeField(blank=True, null=True)
    endTime = models.DateTimeField(blank=True, null=True)
    type = models.CharField(max_length=20, choices=TYPES, blank=False, null=False)


class sslCountDetails(models.Model):
    isSSL = models.BooleanField(default=True)
    monitorDetailsId = models.ForeignKey(monitorDetails, on_delete=models.CASCADE)
    SSLCheckTime = models.DateTimeField(blank=True, null=True)
    SSLDetails = models.TextField()

web-monitoring/sitemonitor/views.py
from django.db.models import Sum, Count, Max, Min, F
from django.shortcuts import render, redirect
import urllib
from django.http import HttpResponse

from rest_framework import generics, status
from rest_framework.response import Response

from .models import monitorDetails, monitorCountDetails, sslCountDetails
from performance.models import performanceCountDetails
from datetime import datetime
from django.core.mail import send_mail
from .utils import timeCalculation, getMinutesBySeconds, scheduler
from urllib.request import ssl, socket
from urllib.parse import urlparse
import json
from performance.views import PerformanceMonitor


# Create your views here.

def monitor(request):
    url = request.POST.get('selected_domain')
    email = request.POST.get('selected_email')

    if url and not email:
        monitorData = monitorDetails.objects.filter(domainName=url)
    elif email and not url:
        monitorData = monitorDetails.objects.filter(email=email)
    elif email and url:
        monitorData = monitorDetails.objects.filter(
            email=email, domainName=url)
    else:
        monitorData = monitorDetails.objects.all()

    domain_list = monitorDetails.objects.order_by().values(
        'domainName').distinct()
    email_list = monitorDetails.objects.order_by().values('email').distinct()
    context = {
        'monitorData': monitorData,
        'domain_list': domain_list,
        'email_list': email_list,
        'selected_url': url,
        'selected_email': email,
    }
    return render(request, "sitemonitor/monitor.html", context)


def addmonitor(request):
    return render(request, "sitemonitor/index.html", {})


class dashboard_performance(generics.GenericAPIView):
    def post(self, request):
        global_data = []
        monitor_record = monitorDetails.objects.filter(
            domainName=request.POST['data']).values_list('id', flat=True)
        perforamce_record = performanceCountDetails.objects.filter(
            monitor_details_id=monitor_record[0]).last()
        performance_detail = json.loads(perforamce_record.performance_data)
        if 'lighthouseResult' in performance_detail:
            if performance_detail.get('lighthouseResult').get(
                    'audits'
                    ).get('first-contentful-paint'):
                performance_dict = {}
                performance_dict.update(
                    {
                        'title': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'first-contentful-paint').get('title'),
                        'numericValue': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'first-contentful-paint').get(
                                'numericValue'),
                        'description': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'first-contentful-paint').get(
                                'description'),
                        'numericUnit': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'first-contentful-paint').get(
                                'numericUnit')
                    }
                )
                global_data.append(performance_dict)
            if performance_detail.get('lighthouseResult').get(
                    'audits'
                    ).get('speed-index'):
                    performance_dict = {}
                    performance_dict.update(
                        {
                            'title': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'speed-index').get('title'),
                            'numericValue': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'speed-index').get('numericValue'),
                            'description': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'speed-index').get('description'),
                            'numericUnit': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'speed-index').get('numericUnit')
                        }
                    )
                    global_data.append(performance_dict)
            if performance_detail.get('lighthouseResult').get(
                        'audits'
                        ).get('largest-contentful-paint'):
                    performance_dict = {}
                    performance_dict.update(
                        {
                            'title': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'largest-contentful-paint').get('title'),
                            'numericValue': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'largest-contentful-paint').get('numericValue'),
                            'description': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'largest-contentful-paint').get('description'),
                            'numericUnit': performance_detail.get(
                                    'lighthouseResult').get('audits').get(
                                    'largest-contentful-paint').get('numericUnit')
                        }
                    )
                    global_data.append(performance_dict)
            if performance_detail.get('lighthouseResult').get(
                    'audits'
                    ).get('interactive'):
                performance_dict = {}
                performance_dict.update(
                    {
                        'title': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'interactive').get('title'),
                        'numericValue': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'interactive').get('numericValue'),
                        'description': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'interactive').get('description'),
                        'numericUnit': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'interactive').get('numericUnit')
                    }
                )
                global_data.append(performance_dict)
            if performance_detail.get('lighthouseResult').get(
                    'audits'
                    ).get('total-blocking-time'):
                performance_dict = {}
                performance_dict.update(
                    {
                        'title': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'total-blocking-time').get('title'),
                        'numericValue': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'total-blocking-time').get('numericValue'),
                        'description': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'total-blocking-time').get('description'),
                        'numericUnit': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'total-blocking-time').get('numericUnit')
                    }
                )
                global_data.append(performance_dict)
            if performance_detail.get('lighthouseResult').get(
                    'audits'
                    ).get('cumulative-layout-shift'):
                performance_dict = {}
                performance_dict.update(
                    {
                        'title': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'cumulative-layout-shift').get('title'),
                        'numericValue': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'cumulative-layout-shift').get('numericValue'),
                        'description': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'cumulative-layout-shift').get('description'),
                        'numericUnit': performance_detail.get(
                                'lighthouseResult').get('audits').get(
                                'cumulative-layout-shift').get('numericUnit')
                    }
                )
                global_data.append(performance_dict)
        context = {
            'global_datas': global_data,
        }
        print("\n\n\n\n context", context)
        return HttpResponse(json.dumps(context))


class ChartDetailsViewSet(generics.GenericAPIView):

    def get(self, request):
        try:
            context = {}
            totalUpTime = 0
            totalDownTime = 0
            downTimeList = []
            upTimeList = []
            totalTimeList = []
            domain_list = []
            totalTime = 0
            id_list = monitorDetails.objects.values_list(
                'id', 'domainName').annotate(dcount=Count('domainName'))

web-monitoring/templates/sitemonitor/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/perfomance.css' %}" rel="stylesheet"/>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 mt-15">
            <div class="card card-custom gutter-b example example-compact">
                <form class="form" action="{% url 'sitemonitor:startmonitor' %}" method="post" id="kt_form_1">
                    <div class="card-body">
                        <div class="form-group">
                            <label>Domain Name:</label>
                            <input type="text" class="form-control form-control-solid" name="domainName"
                                   placeholder="Enter domain name" value="{{monitorData.domainName}}"/>
                            <span class="form-text text-muted">Please enter your domain name</span>
                        </div>
                        <div class="form-group">
                            <label>Interval (seconds):</label>
                            <input type="text" class="form-control form-control-solid" name="interval"
                                   placeholder="Enter interval" value="{{monitorData.interval}}"/>
                            <span class="form-text text-muted">Please enter interval for domain checking</span>
                        </div>
                        <div class="form-group">
                            <label>Email address:</label>
                            <input type="email" class="form-control form-control-solid" name="email"
                                   placeholder="Enter email" value="{{monitorData.email}}"/>
                            <span class="form-text text-muted">We'll never share your email with anyone else</span>
                        </div>
                        <div class="form-group">
                            <label>Notification interval (minutes):</label>
                            <input type="text" class="form-control form-control-solid" name="notificationInterval"
                                   placeholder="Enter notification interval"
                                   value="{{monitorData.notificationInterval}}"/>
                            <span class="form-text text-muted">Please enter interval for notification</span>
                        </div>
                        <div class="form-group">
                            <label>Additional Monitoring:</label>
                            <div class="checkbox-list">
                                <label class="checkbox">
                                     {% if monitorData.SSLEnable == True %}
                                            <input type="checkbox" name="SSLEnable" id="SSLEnable"  checked/>
                                     {% else %}
                                            <input type="checkbox" name="SSLEnable" id="SSLEnable"/>
                                     {% endif %}
                                    <span></span>
                                    SSL
                                </label>
                                {% if monitorData.SSLEnable == True %}
                                    <div id="ssl_content" class="form-group">
                                        {% else %}
                                        <div id="ssl_content" style="display: none;" class="form-group">
                                    {% endif %}
                                    <label>Interval (hours):</label>
                                    <input type="text" class="form-control form-control-solid" name="SSLInterval"
                                           placeholder="Enter ssl check interval"
                                           value="{{monitorData.SSLInterval}}"/>
                                    <span class="form-text text-muted">Please enter interval for ssl check</span>
                                </div>
                                <label class="checkbox">
                                    {% if monitorData.isperfomance == True %}
                                            <input type="checkbox" name="isperfomance" id="isperfomance"  checked/>
                                     {% else %}
                                            <input type="checkbox" name="isperfomance" id="isperfomance"/>
                                     {% endif %}
                                    <span></span>
                                    Performance
                                </label>
                                {% if monitorData.isperfomance == True %}
                                    <div id="performance_content" class="form-group">
                                        {% else %}
                                        <div id="performance_content" style="display: none;" class="form-group">
                                    {% endif %}
                                    <label>Interval (hours):</label>
                                    <input type="text" class="form-control form-control-solid" name="perfomanceinterval"
                                           placeholder="Enter perfomance check interval"
                                           value="{{monitorData.perfomanceinterval}}"/>
                                    <span class="form-text text-muted">Please enter interval for perfomance check</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <button type="button" onclick="location.href ={% url 'monitor:monitor' %}"
                                class="btn btn-secondary">Back
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1400 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#3699FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#E4E6EF", "dark": "#181C32" }, "light": { "white": "#ffffff", "primary": "#E1F0FF", "secondary": "#EBEDF3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#3F4254", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#EBEDF3", "gray-300": "#E4E6EF", "gray-400": "#D1D3E0", "gray-500": "#B5B5C3", "gray-600": "#7E8299", "gray-700": "#5E6278", "gray-800": "#3F4254", "gray-900": "#181C32" } }, "font-family": "Poppins" };




</script>


<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
<script src="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.js' %}"></script>
<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
<script src="{% static 'assets/js/validation.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>

web-monitoring/templates/sitemonitor/monitor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta http-equiv="refresh" content="10">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet"/>

</head>
<body>

<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">Domain Details
                <span class="d-block text-muted pt-2 font-size-sm">Domain monitoring details</span></h3>
        </div>
        <div class="card-toolbar">
            <!--begin::Button-->
            <a href="{% url 'sitemonitor:addmonitor' %}" class="btn btn-primary font-weight-bolder">
											<span class="svg-icon svg-icon-md">
                                                <!--end::Svg Icon-->
											</span>Add New Domain</a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Search Form-->
        <!--begin::Search Form-->
        <form method="post">
            <div class="mb-7">
                <div class="row align-items-center">
                    <div class="col-lg-10 col-xl-9">
                        <div class="row align-items-center">
                            <div class="col-md-4 my-2 my-md-0">
                                <div class="input-icon">
                                    <input type="text" class="form-control" placeholder="Search..."
                                           id="kt_datatable_search_query"/>
                                    <span>
																	<i class="flaticon2-search-1 text-muted"></i>
																</span>
                                </div>
                            </div>
                            <div class="col-md-4 my-2 my-md-0">
                                <div class="d-flex align-items-center">
                                    <label class="mr-3 mb-0 d-none d-md-block">Domain:</label>
                                    <select class="form-control" name="selected_domain">
                                        <option value="">All</option>
                                        {% for domain in domain_list %}
                                        {% if domain.domainName == selected_url %}
                                        <option value={{ domain.domainName }} selected>{{ domain.domainName }}</option>
                                        {% else %}
                                        <option value={{ domain.domainName }}>{{ domain.domainName }}</option>
                                        {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4 my-2 my-md-0">
                                <div class="d-flex align-items-center">
                                    <label class="mr-3 mb-0 d-none d-md-block">Email:</label>
                                    <select class="form-control" name="selected_email">
                                        <option value="">All</option>
                                        {% for data in email_list %}
                                        {% if data.email == selected_email %}
                                        <option value={{ data.email }} selected>{{ data.email }}</option>
                                        {% else %}
                                        <option value={{ data.email }}>{{ data.email }}</option>
                                        {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-xl-3 mt-5 mt-lg-0">
                        <button type="submit" onclick="location.href = {% url 'monitor:monitor' %}"
                                class="btn btn-light-primary px-6 font-weight-bold">Search
                        </button>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Search Form-->
        <!--begin: Datatable-->
        <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
            <thead>
            <tr>
                <th>Domain</th>
                <th>Email</th>
                <th>Start Date</th>
                <th>UpTime (Seconds)</th>
                <th>DownTime (Seconds)</th>
                <th>SSLCheck</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for col in monitorData %}
            <tr>
                <td>{{col.domainName}}</td>
                <td>{{col.email}}</td>
                <td>{{col.startDate}}</td>
                <td>{{col.upTime}}</td>
                <td>{{col.downTime}}</td>
                <td>{{col.SSLEnable}}</td>
                <td>
                    <a href="{% url 'sitemonitor:editmonitor' col.id  %}"><i class="fas fa-pen"
                                                                               ></i></a>
                    <a href="{% url 'sitemonitor:removemonitor' col.id  %}"><i class="fas fa-trash"
                                                                               ></i></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--end: Datatable-->
    </div>
</div>

<script type='text/javascript'>
    var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1400 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#3699FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#E4E6EF", "dark": "#181C32" }, "light": { "white": "#ffffff", "primary": "#E1F0FF", "secondary": "#EBEDF3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#3F4254", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#EBEDF3", "gray-300": "#E4E6EF", "gray-400": "#D1D3E0", "gray-500": "#B5B5C3", "gray-600": "#7E8299", "gray-700": "#5E6278", "gray-800": "#3F4254", "gray-900": "#181C32" } }, "font-family": "Poppins" };

</script>
<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
<script src="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.js' %}"></script>
<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
<!--end::Global Theme Bundle-->
<!--begin::Page Scripts(used by this page)-->
<script src="{% static 'assets/js/pages/crud/ktdatatable/base/html-table.js' %}"></script>
</body>
</html>